CREATE TABLE "tb_user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_auth" INTEGER,
  "email" VARCHAR(100),
  "is_active" BOOLEAN,
  "password" varchar(100),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_event" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_owner" INTEGER,
  "name" VARCHAR(100),
  "description" VARCHAR(100),
  "max_capacity" INTEGER,
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_owner" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_auth" INTEGER,
  "email" VARCHAR(100),
  "is_active" BOOLEAN,
  "password" varchar(100),
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP,
  "deleted_at" TIMESTAMP
);

CREATE TABLE "tb_connections" (
  "id_user_1" INTEGER,
  "id_user_2" INTEGER,
  "created_at" TIMESTAMP,
  PRIMARY KEY ("id_user_1", "id_user_2")
);

CREATE TABLE "tb_auth" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auth_name" VARCHAR(15)
);

CREATE TABLE "tb_questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" TEXT,
  "question_type" VARCHAR(20),
  "is_active" BOOLEAN
);

CREATE TABLE "tb_question_options" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_question" INTEGER NOT NULL,
  "option_text" VARCHAR(100),
  "option_value" NUMERIC
);

CREATE TABLE "tb_user_answers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" INTEGER NOT NULL,
  "id_question_option" INTEGER,
  "id_question" INTEGER NOT NULL,
  "awnser_value" TEXT
);

CREATE TABLE "tb_event_user" (
  "id_event" INTEGER,
  "id_user" INTEGER,
  PRIMARY KEY ("id_event", "id_user")
);

CREATE TABLE "tb_model_versions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" VARCHAR(50) NOT NULL,
  "version" VARCHAR(20) NOT NULL,
  "model_path" VARCHAR(255),
  "accuracy_score" DECIMAL(5,4),
  "training_data_size" INTEGER,
  "created_at" TIMESTAMP,
  "is_active" BOOLEAN
);

CREATE TABLE "tb_training_features" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" INTEGER NOT NULL,
  "user2_id" INTEGER NOT NULL,
  "interests_overlap" DECIMAL(3,2),
  "personality_distance" DECIMAL(5,4),
  "event_id" INTEGER NOT NULL,
  "interaction_success" BOOLEAN,
  "created_at" TIMESTAMP
);

CREATE TABLE "tb_model_predictions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version_id" INTEGER NOT NULL,
  "user1_id" INTEGER,
  "user2_id" INTEGER,
  "predicted_score" DECIMAL(5,4),
  "actual_interaction" BOOLEAN,
  "created_at" TIMESTAMP
);

ALTER TABLE "tb_user" ADD FOREIGN KEY ("id_auth") REFERENCES "tb_auth" ("id");

ALTER TABLE "tb_owner" ADD FOREIGN KEY ("id_auth") REFERENCES "tb_auth" ("id");

ALTER TABLE "tb_event" ADD FOREIGN KEY ("id_owner") REFERENCES "tb_owner" ("id");

ALTER TABLE "tb_event_user" ADD FOREIGN KEY ("id_event") REFERENCES "tb_event" ("id");

ALTER TABLE "tb_event_user" ADD FOREIGN KEY ("id_user") REFERENCES "tb_user" ("id");

ALTER TABLE "tb_connections" ADD FOREIGN KEY ("id_user_1") REFERENCES "tb_user" ("id");

ALTER TABLE "tb_connections" ADD FOREIGN KEY ("id_user_2") REFERENCES "tb_user" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_user") REFERENCES "tb_user" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_question") REFERENCES "tb_questions" ("id");

ALTER TABLE "tb_model_predictions" ADD FOREIGN KEY ("model_version_id") REFERENCES "tb_model_versions" ("id");

ALTER TABLE "tb_training_features" ADD FOREIGN KEY ("user1_id") REFERENCES "tb_owner" ("id");

ALTER TABLE "tb_training_features" ADD FOREIGN KEY ("user2_id") REFERENCES "tb_owner" ("id");

ALTER TABLE "tb_training_features" ADD FOREIGN KEY ("event_id") REFERENCES "tb_event" ("id");

ALTER TABLE "tb_question_options" ADD FOREIGN KEY ("id_question") REFERENCES "tb_questions" ("id");

ALTER TABLE "tb_user_answers" ADD FOREIGN KEY ("id_question_option") REFERENCES "tb_question_options" ("id");
